<script lang="ts">
    	import { getTypography } from "$lib/foundations/typography";
        import * as Select from "$lib/components/ui/select/index.js";

        const destinations = [
    { value: "null", label: "All" },
    { value: "apple", label: "Apple" },
    { value: "banana", label: "Banana" },
    { value: "blueberry", label: "Blueberry" },
    { value: "grapes", label: "Grapes" },
    { value: "pineapple", label: "Pineapple" }
  ];

</script>

<div class="container mx-auto py-8 ">
    <div class="grid grid-cols-12 grid-rows-2 !pb-8 ">
        <Select.Root >
            <Select.Trigger id="idForSelect" data-filter-by="data-oac" class="w-full row-start-2 row-end-2 col-start-9 col-span-7 font-gilroy">
              <Select.Value placeholder="Selecciona tu origen" />
            </Select.Trigger>
            <Select.Content class="bg-white">
              <Select.Group>
                <Select.Label class="font-gilroy">Todos los destinos</Select.Label>
                {#each destinations as Destination}
                  <Select.Item class="font-gilroy " value={Destination.value} label={Destination.label}
                    >{Destination.label}</Select.Item >
                {/each}
              </Select.Group>
            </Select.Content>
            <Select.Input name="favoriteFruit" />
          </Select.Root>

    </div>

  
  
      <ol class="grid gap-3 justify-center" style="grid-template-columns: repeat(auto-fit, minmax(383px,392px));" >
     
        <li class="custom-fares w-full max-w-[400px] h-full"><a class="grid overflow-hidden grid-cols-[8px_117px_auto_8px] grid-rows-[8px_auto_auto_8px] outline outline-1 rounded-2xl outline-grey-300 hover:outline-primary-ultralight focus:outline-2 hover:outline-2 focus:outline-primary-ultralight" href="https://shopping.copaair.com/?roundtrip=true&adults=1&children=0&infants=0&sf=pa&langid=es&date1=2025-01-09&date2=2025-01-16&promocode=&area1=PTY&area2=SJO&advanced_air_search=false&flexible_dates_v2=false&origin=EM" role="button" trfx-booking="" data-oac="PTY" data-dac="SJO" data-departure-date="2025-01-09" data-price="USD 246" data-return-date="2025-01-16" data-title="Panamá a San José" data-sub="Itinerario: Nov 20, 2024 - May 31, 2025" data-promo-code="" data-site-edition="es-PA" data-currency-code="USD"><img class="w-full h-full col-start-1 col-end-3 row-span-full object-cover" src="https://www.copaair.com/promotions/airtrafix-pics/portrait/SJO-1-270x360.jpg" alt="San José (SJO)"> <span class="mx-2 mb-2 col-start-3 col-end-3 row-start-2 row-end-2 flex flex-col gap-1" data-svelte-h="svelte-1dmh4f3"><span class="text-b font-bold flex flex-col font-gilroy text-primary h-auto"><span class="">Panamá (PTY) a</span> <span class="">San José (SJO)</span></span> <span class="flex h-auto items-center gap-2"><img src="https://www.copaair.com/promotions/destinations/icons/calendar-icon.svg" class="h-[10.3px] w-[11.6px]" alt="date"> <span class="font-suisse font-normal text-d3 text-grey-600">Ida y vuelta<br>Nov 20, 2024 - May 31, 2025</span></span></span> <span class="mx-2 mt-2 col-start-3 col-end-3 row-start-3 row-end-3 "><span class="flex flex-col items-end grid-rows-subgrid"><span class="font-normal text-d1 font-suisse text-grey-600 line-through self-end">USD 270</span> <span class="gap-y-2" data-svelte-h="svelte-11zovdb"><span class="font-suisse font-normal text-d3 text-grey-600">desde <span class="text-u2 font-gilroy font-bold text-primary lg:text-u1">USD 246<sup>*</sup></span></span></span> <span class="font-suisse font-normal text-d3 text-grey-600" data-svelte-h="svelte-mgotms">Impuestos desde USD 400</span></span></span></a></li> 
<li class="custom-fares w-full max-w-[400px] h-full"><a class="grid overflow-hidden grid-cols-[8px_117px_auto_8px] grid-rows-[8px_auto_auto_8px] outline outline-1 rounded-2xl outline-grey-300 hover:outline-primary-ultralight focus:outline-2 hover:outline-2 focus:outline-primary-ultralight" href="https://shopping.copaair.com/?roundtrip=true&adults=1&children=0&infants=0&sf=pa&langid=es&date1=2025-01-23&date2=2025-01-28&promocode=&area1=PTY&area2=XPL&advanced_air_search=false&flexible_dates_v2=false&origin=EM" role="button" trfx-booking="" data-oac="PTY" data-dac="XPL" data-departure-date="2025-01-23" data-price="USD 304" data-return-date="2025-01-28" data-title="Panamá a Comayagua, Tegucigalpa" data-sub="Itinerario: Nov 20, 2024 - May 31, 2025" data-promo-code="" data-site-edition="es-PA" data-currency-code="USD"><img class="w-full h-full col-start-1 col-end-3 row-span-full object-cover" src="https://www.copaair.com/promotions/airtrafix-pics/portrait/XPL-1-270x360.jpg" alt="Comayagua, Tegucigalpa (XPL)"> <span class="mx-2 mb-2 col-start-3 col-end-3 row-start-2 row-end-2 flex flex-col gap-1" data-svelte-h="svelte-1dmh4f3"><span class="text-b font-bold flex flex-col font-gilroy text-primary h-auto"><span class="">Panamá (PTY) a</span> <span class="">Comayagua, Tegucigalpa (XPL)</span></span> <span class="flex h-auto items-center gap-2"><img src="https://www.copaair.com/promotions/destinations/icons/calendar-icon.svg" class="h-[10.3px] w-[11.6px]" alt="date"> <span class="font-suisse font-normal text-d3 text-grey-600">Ida y vuelta<br>Nov 20, 2024 - May 31, 2025</span></span></span> <span class="mx-2 mt-2 col-start-3 col-end-3 row-start-3 row-end-3 "><span class="flex flex-col items-end grid-rows-subgrid"><span class="font-normal text-d1 font-suisse text-grey-600 line-through self-end">USD 339</span> <span class="gap-y-2" data-svelte-h="svelte-11zovdb"><span class="font-suisse font-normal text-d3 text-grey-600">desde <span class="text-u2 font-gilroy font-bold text-primary lg:text-u1">USD 304<sup>*</sup></span></span></span> <span class="font-suisse font-normal text-d3 text-grey-600" data-svelte-h="svelte-mgotms"></span></span></span></a></li> 
<li class="custom-fares w-full max-w-[400px] h-full"><a class="grid overflow-hidden grid-cols-[8px_117px_auto_8px] grid-rows-[8px_auto_auto_8px] outline outline-1 rounded-2xl outline-grey-300 hover:outline-primary-ultralight focus:outline-2 hover:outline-2 focus:outline-primary-ultralight" href="https://shopping.copaair.com/?roundtrip=true&adults=1&children=0&infants=0&sf=pa&langid=es&date1=2025-01-11&date2=2025-01-18&promocode=&area1=PTY&area2=AUA&advanced_air_search=false&flexible_dates_v2=false&origin=EM" role="button" trfx-booking="" data-oac="PTY" data-dac="AUA" data-departure-date="2025-01-11" data-price="USD 323" data-return-date="2025-01-18" data-title="Panamá a Aruba" data-sub="Itinerario: Nov 20, 2024 - May 31, 2025" data-promo-code="" data-site-edition="es-PA" data-currency-code="USD"><img class="w-full h-full col-start-1 col-end-3 row-span-full object-cover" src="https://www.copaair.com/promotions/airtrafix-pics/portrait/AUA-1-270x360.jpg" alt="Aruba (AUA)"> <span class="mx-2 mb-2 col-start-3 col-end-3 row-start-2 row-end-2 flex flex-col gap-1" data-svelte-h="svelte-1dmh4f3"><span class="text-b font-bold flex flex-col font-gilroy text-primary h-auto"><span class="">Panamá (PTY) a</span> <span class="">Aruba (AUA)</span></span> <span class="flex h-auto items-center gap-2"><img src="https://www.copaair.com/promotions/destinations/icons/calendar-icon.svg" class="h-[10.3px] w-[11.6px]" alt="date"> <span class="font-suisse font-normal text-d3 text-grey-600">Ida y vuelta<br>Nov 20, 2024 - May 31, 2025</span></span></span> <span class="mx-2 mt-2 col-start-3 col-end-3 row-start-3 row-end-3 "><span class="flex flex-col items-end grid-rows-subgrid"><span class="font-normal text-d1 font-suisse text-grey-600 line-through self-end">USD 361</span> <span class="gap-y-2" data-svelte-h="svelte-11zovdb"><span class="font-suisse font-normal text-d3 text-grey-600">desde <span class="text-u2 font-gilroy font-bold text-primary lg:text-u1">USD 323<sup>*</sup></span></span></span> <span class="font-suisse font-normal text-d3 text-grey-600" data-svelte-h="svelte-mgotms"></span></span></span></a></li> 
<li class="custom-fares w-full max-w-[400px] h-full"><a class="grid overflow-hidden grid-cols-[8px_117px_auto_8px] grid-rows-[8px_auto_auto_8px] outline outline-1 rounded-2xl outline-grey-300 hover:outline-primary-ultralight focus:outline-2 hover:outline-2 focus:outline-primary-ultralight" href="https://shopping.copaair.com/?roundtrip=true&adults=1&children=0&infants=0&sf=pa&langid=es&date1=2025-01-25&date2=2025-02-01&promocode=&area1=PTY&area2=PUJ&advanced_air_search=false&flexible_dates_v2=false&origin=EM" role="button" trfx-booking="" data-oac="PTY" data-dac="PUJ" data-departure-date="2025-01-25" data-price="USD 324" data-return-date="2025-02-01" data-title="Panamá a Punta Cana" data-sub="Itinerario: Nov 20, 2024 - May 31, 2025" data-promo-code="" data-site-edition="es-PA" data-currency-code="USD"><img class="w-full h-full col-start-1 col-end-3 row-span-full object-cover" src="https://www.copaair.com/promotions/airtrafix-pics/portrait/PUJ-1-270x360.jpg" alt="Punta Cana (PUJ)"> <span class="mx-2 mb-2 col-start-3 col-end-3 row-start-2 row-end-2 flex flex-col gap-1" data-svelte-h="svelte-1dmh4f3"><span class="text-b font-bold flex flex-col font-gilroy text-primary h-auto"><span class="">Panamá (PTY) a</span> <span class="">Punta Cana (PUJ)</span></span> <span class="flex h-auto items-center gap-2"><img src="https://www.copaair.com/promotions/destinations/icons/calendar-icon.svg" class="h-[10.3px] w-[11.6px]" alt="date"> <span class="font-suisse font-normal text-d3 text-grey-600">Ida y vuelta<br>Nov 20, 2024 - May 31, 2025</span></span></span> <span class="mx-2 mt-2 col-start-3 col-end-3 row-start-3 row-end-3 "><span class="flex flex-col items-end grid-rows-subgrid"><span class="font-normal text-d1 font-suisse text-grey-600 line-through self-end">USD 353</span> <span class="gap-y-2" data-svelte-h="svelte-11zovdb"><span class="font-suisse font-normal text-d3 text-grey-600">desde <span class="text-u2 font-gilroy font-bold text-primary lg:text-u1">USD 324<sup>*</sup></span></span></span> <span class="font-suisse font-normal text-d3 text-grey-600" data-svelte-h="svelte-mgotms"></span></span></span></a></li> 
<li class="custom-fares w-full max-w-[400px] h-full"><a class="grid overflow-hidden grid-cols-[8px_117px_auto_8px] grid-rows-[8px_auto_auto_8px] outline outline-1 rounded-2xl outline-grey-300 hover:outline-primary-ultralight focus:outline-2 hover:outline-2 focus:outline-primary-ultralight" href="https://shopping.copaair.com/?roundtrip=true&adults=1&children=0&infants=0&sf=pa&langid=es&date1=2025-02-09&date2=2025-02-17&promocode=&area1=PTY&area2=NAS&advanced_air_search=false&flexible_dates_v2=false&origin=EM" role="button" trfx-booking="" data-oac="PTY" data-dac="NAS" data-departure-date="2025-02-09" data-price="USD 332" data-return-date="2025-02-17" data-title="Panamá a Nassau" data-sub="Itinerario: Nov 20, 2024 - May 31, 2025" data-promo-code="" data-site-edition="es-PA" data-currency-code="USD"><img class="w-full h-full col-start-1 col-end-3 row-span-full object-cover" src="https://www.copaair.com/promotions/airtrafix-pics/portrait/NAS-1-270x360.jpg" alt="Nassau (NAS)"> <span class="mx-2 mb-2 col-start-3 col-end-3 row-start-2 row-end-2 flex flex-col gap-1" data-svelte-h="svelte-1dmh4f3"><span class="text-b font-bold flex flex-col font-gilroy text-primary h-auto"><span class="">Panamá (PTY) a</span> <span class="">Nassau (NAS)</span></span> <span class="flex h-auto items-center gap-2"><img src="https://www.copaair.com/promotions/destinations/icons/calendar-icon.svg" class="h-[10.3px] w-[11.6px]" alt="date"> <span class="font-suisse font-normal text-d3 text-grey-600">Ida y vuelta<br>Nov 20, 2024 - May 31, 2025</span></span></span> <span class="mx-2 mt-2 col-start-3 col-end-3 row-start-3 row-end-3 "><span class="flex flex-col items-end grid-rows-subgrid"><span class="font-normal text-d1 font-suisse text-grey-600 line-through self-end">USD 364</span> <span class="gap-y-2" data-svelte-h="svelte-11zovdb"><span class="font-suisse font-normal text-d3 text-grey-600">desde <span class="text-u2 font-gilroy font-bold text-primary lg:text-u1">USD 332<sup>*</sup></span></span></span> <span class="font-suisse font-normal text-d3 text-grey-600" data-svelte-h="svelte-mgotms"></span></span></span></a></li> 
<li class="custom-fares w-full max-w-[400px] h-full"><a class="grid overflow-hidden grid-cols-[8px_117px_auto_8px] grid-rows-[8px_auto_auto_8px] outline outline-1 rounded-2xl outline-grey-300 hover:outline-primary-ultralight focus:outline-2 hover:outline-2 focus:outline-primary-ultralight" href="https://shopping.copaair.com/?roundtrip=true&adults=1&children=0&infants=0&sf=pa&langid=es&date1=2025-02-11&date2=2025-02-17&promocode=&area1=PTY&area2=CUR&advanced_air_search=false&flexible_dates_v2=false&origin=EM" role="button" trfx-booking="" data-oac="PTY" data-dac="CUR" data-departure-date="2025-02-11" data-price="USD 333" data-return-date="2025-02-17" data-title="Panamá a Curazao" data-sub="Itinerario: Nov 20, 2024 - May 31, 2025" data-promo-code="" data-site-edition="es-PA" data-currency-code="USD"><img class="w-full h-full col-start-1 col-end-3 row-span-full object-cover" src="https://www.copaair.com/promotions/airtrafix-pics/portrait/CUR-1-270x360.jpg" alt="Curazao (CUR)"> <span class="mx-2 mb-2 col-start-3 col-end-3 row-start-2 row-end-2 flex flex-col gap-1" data-svelte-h="svelte-1dmh4f3"><span class="text-b font-bold flex flex-col font-gilroy text-primary h-auto"><span class="">Panamá (PTY) a</span> <span class="">Curazao (CUR)</span></span> <span class="flex h-auto items-center gap-2"><img src="https://www.copaair.com/promotions/destinations/icons/calendar-icon.svg" class="h-[10.3px] w-[11.6px]" alt="date"> <span class="font-suisse font-normal text-d3 text-grey-600">Ida y vuelta<br>Nov 20, 2024 - May 31, 2025</span></span></span> <span class="mx-2 mt-2 col-start-3 col-end-3 row-start-3 row-end-3 "><span class="flex flex-col items-end grid-rows-subgrid"><span class="font-normal text-d1 font-suisse text-grey-600 line-through self-end">USD 352</span> <span class="gap-y-2" data-svelte-h="svelte-11zovdb"><span class="font-suisse font-normal text-d3 text-grey-600">desde <span class="text-u2 font-gilroy font-bold text-primary lg:text-u1">USD 333<sup>*</sup></span></span></span> <span class="font-suisse font-normal text-d3 text-grey-600" data-svelte-h="svelte-mgotms"></span></span></span></a></li> 
<li class="custom-fares w-full max-w-[400px] h-full"><a class="grid overflow-hidden grid-cols-[8px_117px_auto_8px] grid-rows-[8px_auto_auto_8px] outline outline-1 rounded-2xl outline-grey-300 hover:outline-primary-ultralight focus:outline-2 hover:outline-2 focus:outline-primary-ultralight" href="https://shopping.copaair.com/?roundtrip=true&adults=1&children=0&infants=0&sf=pa&langid=es&date1=2025-02-11&date2=2025-02-17&promocode=&area1=PTY&area2=BGI&advanced_air_search=false&flexible_dates_v2=false&origin=EM" role="button" trfx-booking="" data-oac="PTY" data-dac="BGI" data-departure-date="2025-02-11" data-price="USD 339" data-return-date="2025-02-17" data-title="Panamá a Bridgetown" data-sub="Itinerario: Nov 20, 2024 - May 31, 2025" data-promo-code="" data-site-edition="es-PA" data-currency-code="USD"><img class="w-full h-full col-start-1 col-end-3 row-span-full object-cover" src="https://www.copaair.com/promotions/airtrafix-pics/portrait/BGI-1-270x360.jpg" alt="Bridgetown (BGI)"> <span class="mx-2 mb-2 col-start-3 col-end-3 row-start-2 row-end-2 flex flex-col gap-1" data-svelte-h="svelte-1dmh4f3"><span class="text-b font-bold flex flex-col font-gilroy text-primary h-auto"><span class="">Panamá (PTY) a</span> <span class="">Bridgetown (BGI)</span></span> <span class="flex h-auto items-center gap-2"><img src="https://www.copaair.com/promotions/destinations/icons/calendar-icon.svg" class="h-[10.3px] w-[11.6px]" alt="date"> <span class="font-suisse font-normal text-d3 text-grey-600">Ida y vuelta<br>Nov 20, 2024 - May 31, 2025</span></span></span> <span class="mx-2 mt-2 col-start-3 col-end-3 row-start-3 row-end-3 "><span class="flex flex-col items-end grid-rows-subgrid"><span class="font-normal text-d1 font-suisse text-grey-600 line-through self-end">USD 371</span> <span class="gap-y-2" data-svelte-h="svelte-11zovdb"><span class="font-suisse font-normal text-d3 text-grey-600">desde <span class="text-u2 font-gilroy font-bold text-primary lg:text-u1">USD 339<sup>*</sup></span></span></span> <span class="font-suisse font-normal text-d3 text-grey-600" data-svelte-h="svelte-mgotms"></span></span></span></a></li> 
<li class="custom-fares w-full max-w-[400px] h-full"><a class="grid overflow-hidden grid-cols-[8px_117px_auto_8px] grid-rows-[8px_auto_auto_8px] outline outline-1 rounded-2xl outline-grey-300 hover:outline-primary-ultralight focus:outline-2 hover:outline-2 focus:outline-primary-ultralight" href="https://shopping.copaair.com/?roundtrip=true&adults=1&children=0&infants=0&sf=pa&langid=es&date1=2025-01-13&date2=2025-01-20&promocode=&area1=PTY&area2=SJU&advanced_air_search=false&flexible_dates_v2=false&origin=EM" role="button" trfx-booking="" data-oac="PTY" data-dac="SJU" data-departure-date="2025-01-13" data-price="USD 352" data-return-date="2025-01-20" data-title="Panamá a San Juan" data-sub="Itinerario: Nov 20, 2024 - May 31, 2025" data-promo-code="" data-site-edition="es-PA" data-currency-code="USD"><img class="w-full h-full col-start-1 col-end-3 row-span-full object-cover" src="https://www.copaair.com/promotions/airtrafix-pics/portrait/SJU-1-270x360.jpg" alt="San Juan (SJU)"> <span class="mx-2 mb-2 col-start-3 col-end-3 row-start-2 row-end-2 flex flex-col gap-1" data-svelte-h="svelte-1dmh4f3"><span class="text-b font-bold flex flex-col font-gilroy text-primary h-auto"><span class="">Panamá (PTY) a</span> <span class="">San Juan (SJU)</span></span> <span class="flex h-auto items-center gap-2"><img src="https://www.copaair.com/promotions/destinations/icons/calendar-icon.svg" class="h-[10.3px] w-[11.6px]" alt="date"> <span class="font-suisse font-normal text-d3 text-grey-600">Ida y vuelta<br>Nov 20, 2024 - May 31, 2025</span></span></span> <span class="mx-2 mt-2 col-start-3 col-end-3 row-start-3 row-end-3 "><span class="flex flex-col items-end grid-rows-subgrid"><span class="font-normal text-d1 font-suisse text-grey-600 line-through self-end">USD 414</span> <span class="gap-y-2" data-svelte-h="svelte-11zovdb"><span class="font-suisse font-normal text-d3 text-grey-600">desde <span class="text-u2 font-gilroy font-bold text-primary lg:text-u1">USD 352<sup>*</sup></span></span></span> <span class="font-suisse font-normal text-d3 text-grey-600" data-svelte-h="svelte-mgotms"></span></span></span></a></li> 
<li class="custom-fares w-full max-w-[400px] h-full"><a class="grid overflow-hidden grid-cols-[8px_117px_auto_8px] grid-rows-[8px_auto_auto_8px] outline outline-1 rounded-2xl outline-grey-300 hover:outline-primary-ultralight focus:outline-2 hover:outline-2 focus:outline-primary-ultralight" href="https://shopping.copaair.com/?roundtrip=true&adults=1&children=0&infants=0&sf=pa&langid=es&date1=2025-01-21&date2=2025-01-26&promocode=&area1=PTY&area2=SXM&advanced_air_search=false&flexible_dates_v2=false&origin=EM" role="button" trfx-booking="" data-oac="PTY" data-dac="SXM" data-departure-date="2025-01-21" data-price="USD 357" data-return-date="2025-01-26" data-title="Panamá a St Maarten" data-sub="Itinerario: Nov 20, 2024 - May 31, 2025" data-promo-code="" data-site-edition="es-PA" data-currency-code="USD"><img class="w-full h-full col-start-1 col-end-3 row-span-full object-cover" src="https://www.copaair.com/promotions/airtrafix-pics/portrait/SXM-1-270x360.jpg" alt="St Maarten (SXM)"> <span class="mx-2 mb-2 col-start-3 col-end-3 row-start-2 row-end-2 flex flex-col gap-1" data-svelte-h="svelte-1dmh4f3"><span class="text-b font-bold flex flex-col font-gilroy text-primary h-auto"><span class="">Panamá (PTY) a</span> <span class="">St Maarten (SXM)</span></span> <span class="flex h-auto items-center gap-2"><img src="https://www.copaair.com/promotions/destinations/icons/calendar-icon.svg" class="h-[10.3px] w-[11.6px]" alt="date"> <span class="font-suisse font-normal text-d3 text-grey-600">Ida y vuelta<br>Nov 20, 2024 - May 31, 2025</span></span></span> <span class="mx-2 mt-2 col-start-3 col-end-3 row-start-3 row-end-3 "><span class="flex flex-col items-end grid-rows-subgrid"><span class="font-normal text-d1 font-suisse text-grey-600 line-through self-end">USD 379</span> <span class="gap-y-2" data-svelte-h="svelte-11zovdb"><span class="font-suisse font-normal text-d3 text-grey-600">desde <span class="text-u2 font-gilroy font-bold text-primary lg:text-u1">USD 357<sup>*</sup></span></span></span> <span class="font-suisse font-normal text-d3 text-grey-600" data-svelte-h="svelte-mgotms"></span></span></span></a></li> 
<li class="custom-fares w-full max-w-[400px] h-full"><a class="grid overflow-hidden grid-cols-[8px_117px_auto_8px] grid-rows-[8px_auto_auto_8px] outline outline-1 rounded-2xl outline-grey-300 hover:outline-primary-ultralight focus:outline-2 hover:outline-2 focus:outline-primary-ultralight" href="https://shopping.copaair.com/?roundtrip=true&adults=1&children=0&infants=0&sf=pa&langid=es&date1=2025-01-20&date2=2025-01-27&promocode=&area1=PTY&area2=BZE&advanced_air_search=false&flexible_dates_v2=false&origin=EM" role="button" trfx-booking="" data-oac="PTY" data-dac="BZE" data-departure-date="2025-01-20" data-price="USD 375" data-return-date="2025-01-27" data-title="Panamá a Belice" data-sub="Itinerario: Nov 20, 2024 - May 31, 2025" data-promo-code="" data-site-edition="es-PA" data-currency-code="USD"><img class="w-full h-full col-start-1 col-end-3 row-span-full object-cover" src="https://www.copaair.com/promotions/airtrafix-pics/portrait/BZE-1-270x360.jpg" alt="Belice (BZE)"> <span class="mx-2 mb-2 col-start-3 col-end-3 row-start-2 row-end-2 flex flex-col gap-1" data-svelte-h="svelte-1dmh4f3"><span class="text-b font-bold flex flex-col font-gilroy text-primary h-auto"><span class="">Panamá (PTY) a</span> <span class="">Belice (BZE)</span></span> <span class="flex h-auto items-center gap-2"><img src="https://www.copaair.com/promotions/destinations/icons/calendar-icon.svg" class="h-[10.3px] w-[11.6px]" alt="date"> <span class="font-suisse font-normal text-d3 text-grey-600">Ida y vuelta<br>Nov 20, 2024 - May 31, 2025</span></span></span> <span class="mx-2 mt-2 col-start-3 col-end-3 row-start-3 row-end-3 "><span class="flex flex-col items-end grid-rows-subgrid"><span class="font-normal text-d1 font-suisse text-grey-600 line-through self-end">USD 418</span> <span class="gap-y-2" data-svelte-h="svelte-11zovdb"><span class="font-suisse font-normal text-d3 text-grey-600">desde <span class="text-u2 font-gilroy font-bold text-primary lg:text-u1">USD 375<sup>*</sup></span></span></span> <span class="font-suisse font-normal text-d3 text-grey-600" data-svelte-h="svelte-mgotms"></span></span></span></a></li> 
        
    
     
       </ol>
  
    <div class="text-center mx-auto flex justify-center pt-4">
          <button  id="atlantaholderpaginator" class={getTypography('body','body','min-w-[4.563rem] max-h-[5rem] flex items-center justify-center text-center outline-offset-4 outline-2 border active:outline focus:outline disabled:cursor-not-allowed disabled:outline-0 px-4 py-[0.625rem] rounded-[2.5rem] gap-1 text-d1 *:max-h-5 bg-primary text-common-white outline-primary border-primary hover:bg-primary-ultradark active:bg-primary focus:bg-primary-ultradark disabled:text-grey-500 disabled:bg-grey-100')}>Ver más</button>
        </div>
    <p class={getTypography('body','body','text-grey-600 text-center pt-4')} >
          *Aplican restricciones, consulte nuestros 
          <a href="https://www.copaair.com/es/vuelos-terminos-y-condiciones" target="_blank" rel="noopener"><span class={getTypography('body','body','text-primary hover:!underline')}>T&eacute;rminos y condiciones</span>
          </a>.</p>

  </div>
